version: '3.8'

services:
  api:
    build: .
    container_name: api-java
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
        - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME} -h localhost -p 5432"]
        interval: 10s
        timeout: 5s
        retries: 5
    restart: unless-stopped

networks:
    app-network:
        driver: bridge

volumes:
  postgres-data:
